# Generated by Django 4.1.5 on 2023-01-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0002_rename_cliente_clientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='Cedula',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='apellido',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
