# Generated by Django 4.1.5 on 2023-01-29 06:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cliente', '0003_alter_clientes_cedula_alter_clientes_apellido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensualidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Pago')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_finalizacion', models.DateField(default=django.utils.timezone.now)),
                ('cliente', models.ForeignKey(help_text='seleccione al cliente ingresado', on_delete=django.db.models.deletion.PROTECT, to='Cliente.clientes')),
            ],
            options={
                'verbose_name': 'Mensualidad',
                'verbose_name_plural': 'Mensualidades',
                'ordering': ('cliente',),
            },
        ),
    ]
